export const PERMISSIONS = {
  CRM_READ: "crm.read",
  CRM_MANAGE: "crm.manage",

  PROGRAM_READ: "program.read",
  PROGRAM_MANAGE: "program.manage",

  ADMIN_REQUEST_CREATE: "admin_request.create",
  ADMIN_REQUEST_READ: "admin_request.read",
  ADMIN_REQUEST_VALIDATE: "admin_request.validate",

  PLAN_READ: "plan.read",
  PLAN_MANAGE: "plan.manage",

  EVALUATION_READ: "evaluation.read",
  EVALUATION_MANAGE: "evaluation.manage",

  COURRIER_READ: "courrier.read",
  COURRIER_MANAGE: "courrier.manage",

  PROJECT_CREATE: "project.create",
  PROJECT_READ: "project.read",
  PROJECT_UPDATE: "project.update",
  PROJECT_DELETE: "project.delete",
  PROJECT_VALIDATE: "project.validate",
  PROJECT_EXPORT: "project.export",
  PROJECT_MANAGE_MEMBERS: "project.manage_members",

  SECTION_CREATE: "section.create",
  SECTION_UPDATE: "section.update",
  SECTION_DELETE: "section.delete",

  TASK_CREATE: "task.create",
  TASK_READ: "task.read",
  TASK_UPDATE: "task.update",
  TASK_DELETE: "task.delete",
  TASK_ASSIGN: "task.assign",
  TASK_VALIDATE: "task.validate",
  TASK_COMMENT: "task.comment",
  TASK_EXPORT: "task.export",

  WORKFLOW_MANAGE: "workflow.manage",

  MEETING_CREATE: "meeting.create",
  MEETING_READ: "meeting.read",
  MEETING_UPDATE: "meeting.update",
  MEETING_DELETE: "meeting.delete",
  MEETING_MANAGE_PARTICIPANTS: "meeting.manage_participants",

  DOCUMENT_CREATE: "document.create",
  DOCUMENT_READ: "document.read",
  DOCUMENT_UPDATE: "document.update",
  DOCUMENT_DELETE: "document.delete",
  DOCUMENT_MANAGE_FOLDERS: "document.manage_folders",

  KNOWLEDGE_READ: "knowledge.read",
  KNOWLEDGE_CREATE: "knowledge.create",
  KNOWLEDGE_UPDATE: "knowledge.update",
  KNOWLEDGE_MANAGE_CATEGORIES: "knowledge.manage_categories",

  LEAVE_CREATE: "leave.create",
  LEAVE_MANAGE: "leave.manage",
  EVENT_CREATE: "event.create",

  OBJECTIVE_CREATE: "objective.create",
  OBJECTIVE_READ: "objective.read",
  OBJECTIVE_UPDATE: "objective.update",
  OBJECTIVE_DELETE: "objective.delete",

  WORKLOAD_READ: "workload.read",
  WORKLOAD_MANAGE: "workload.manage",

  MESSAGE_CREATE: "message.create",
  MESSAGE_READ: "message.read",

  AUTOMATION_MANAGE: "automation.manage",
  AUTOMATION_READ: "automation.read",

  DASHBOARD_READ: "dashboard.read",

  REPORT_EXPORT: "report.export",

  SECURITY_AUDIT_READ: "security.audit.read",

  INTEGRATION_MANAGE: "integration.manage",

  DEPARTMENT_MANAGE: "department.manage",

  ADMINISTRATION_ACCESS: "administration.access",
  ADMINISTRATION_USERS_MANAGE: "administration.users.manage",
  ADMINISTRATION_ROLES_MANAGE: "administration.roles.manage",

  // Extension v2.0
  GOVERNANCE_READ: "governance.read",
  GOVERNANCE_MANAGE: "governance.manage",

  PROCESS_READ: "process.read",
  PROCESS_MANAGE: "process.manage",

  RISK_READ: "risk.read",
  RISK_MANAGE: "risk.manage",

  // Extension V2.2 §22-25 — Multi-entites / Consolidation
  ENTITY_MANAGE: "entity.manage",
  ENTITY_VIEW_ALL: "entity.view_all",

  // Extension V2.2 §29 — Centre de commande executif (reserve aux dirigeants)
  EXECUTIVE_VIEW: "executive.view",

  // Extension V2.2 §33-34 — Marketplace / cles API
  MARKETPLACE_MANAGE: "marketplace.manage",
  API_MANAGE: "api.manage",

  // Extension V2.2 §36-37 — Sessions/appareils, sauvegarde/restauration, corbeille
  SESSION_MANAGE: "session.manage",
  DATA_BACKUP_MANAGE: "data.backup_manage",
  TRASH_MANAGE: "trash.manage",

  // Extension V2.2 §41-43 — Matrice de decision, gouvernance IA
  DECISION_MATRIX_MANAGE: "decision_matrix.manage",
  AI_GOVERNANCE_APPROVE: "ai_governance.approve",

  // Extension V3.0 §17-18 — Memoire organisationnelle
  MEMORY_READ: "memory.read",
  MEMORY_MANAGE: "memory.manage",

  // Extension V3.0 §24 — Talent & Succession Planning
  SUCCESSION_READ: "succession.read",
  SUCCESSION_MANAGE: "succession.manage",

  // Extension V3.0 §27 — Multi-Organization Platform (registre des tenants,
  // reserve au super-admin de la plateforme, pas aux administrateurs d'une
  // organisation individuelle).
  PLATFORM_MANAGE: "platform.manage",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG: {
  key: PermissionKey;
  label: string;
  category: string;
}[] = [
  { key: PERMISSIONS.CRM_READ, label: "Consulter le CRM (contacts, organisations, pipeline)", category: "CRM" },
  { key: PERMISSIONS.CRM_MANAGE, label: "Gérer le CRM (contacts, organisations, opportunités, interactions)", category: "CRM" },

  { key: PERMISSIONS.PROGRAM_READ, label: "Consulter les programmes", category: "Programmes" },
  { key: PERMISSIONS.PROGRAM_MANAGE, label: "Créer et gérer les programmes", category: "Programmes" },

  { key: PERMISSIONS.ADMIN_REQUEST_CREATE, label: "Soumettre une demande administrative", category: "Demandes administratives" },
  { key: PERMISSIONS.ADMIN_REQUEST_READ, label: "Consulter les demandes administratives", category: "Demandes administratives" },
  { key: PERMISSIONS.ADMIN_REQUEST_VALIDATE, label: "Approuver/refuser une demande administrative", category: "Demandes administratives" },

  { key: PERMISSIONS.PLAN_READ, label: "Consulter les plans de planification", category: "Planification" },
  { key: PERMISSIONS.PLAN_MANAGE, label: "Créer et gérer les plans de planification", category: "Planification" },

  { key: PERMISSIONS.EVALUATION_READ, label: "Consulter les évaluations de performance", category: "Évaluations de performance" },
  { key: PERMISSIONS.EVALUATION_MANAGE, label: "Mener et soumettre des évaluations de performance", category: "Évaluations de performance" },

  { key: PERMISSIONS.COURRIER_READ, label: "Consulter le registre du courrier", category: "Courrier" },
  { key: PERMISSIONS.COURRIER_MANAGE, label: "Enregistrer et gérer le courrier", category: "Courrier" },

  { key: PERMISSIONS.PROJECT_CREATE, label: "Créer un projet", category: "Projets" },
  { key: PERMISSIONS.PROJECT_READ, label: "Consulter les projets", category: "Projets" },
  { key: PERMISSIONS.PROJECT_UPDATE, label: "Modifier un projet", category: "Projets" },
  { key: PERMISSIONS.PROJECT_DELETE, label: "Supprimer un projet", category: "Projets" },
  { key: PERMISSIONS.PROJECT_VALIDATE, label: "Valider un projet", category: "Projets" },
  { key: PERMISSIONS.PROJECT_EXPORT, label: "Exporter un projet", category: "Projets" },
  { key: PERMISSIONS.PROJECT_MANAGE_MEMBERS, label: "Gérer les membres du projet", category: "Projets" },

  { key: PERMISSIONS.SECTION_CREATE, label: "Créer une phase/sous-phase/lot", category: "Projets" },
  { key: PERMISSIONS.SECTION_UPDATE, label: "Modifier une phase/sous-phase/lot", category: "Projets" },
  { key: PERMISSIONS.SECTION_DELETE, label: "Supprimer une phase/sous-phase/lot", category: "Projets" },

  { key: PERMISSIONS.TASK_CREATE, label: "Créer une tâche", category: "Tâches" },
  { key: PERMISSIONS.TASK_READ, label: "Consulter les tâches", category: "Tâches" },
  { key: PERMISSIONS.TASK_UPDATE, label: "Modifier une tâche", category: "Tâches" },
  { key: PERMISSIONS.TASK_DELETE, label: "Supprimer une tâche", category: "Tâches" },
  { key: PERMISSIONS.TASK_ASSIGN, label: "Assigner une tâche", category: "Tâches" },
  { key: PERMISSIONS.TASK_VALIDATE, label: "Valider une tâche", category: "Tâches" },
  { key: PERMISSIONS.TASK_COMMENT, label: "Commenter une tâche", category: "Tâches" },
  { key: PERMISSIONS.TASK_EXPORT, label: "Exporter les tâches", category: "Tâches" },
  { key: PERMISSIONS.WORKFLOW_MANAGE, label: "Configurer les circuits de validation", category: "Tâches" },

  { key: PERMISSIONS.MEETING_CREATE, label: "Créer une réunion", category: "Réunions" },
  { key: PERMISSIONS.MEETING_READ, label: "Consulter les réunions", category: "Réunions" },
  { key: PERMISSIONS.MEETING_UPDATE, label: "Modifier une réunion", category: "Réunions" },
  { key: PERMISSIONS.MEETING_DELETE, label: "Supprimer une réunion", category: "Réunions" },
  { key: PERMISSIONS.MEETING_MANAGE_PARTICIPANTS, label: "Gérer les participants", category: "Réunions" },

  { key: PERMISSIONS.DOCUMENT_CREATE, label: "Ajouter un document", category: "Documents" },
  { key: PERMISSIONS.DOCUMENT_READ, label: "Consulter les documents", category: "Documents" },
  { key: PERMISSIONS.DOCUMENT_UPDATE, label: "Modifier un document (nouvelle version)", category: "Documents" },
  { key: PERMISSIONS.DOCUMENT_DELETE, label: "Supprimer un document", category: "Documents" },
  { key: PERMISSIONS.DOCUMENT_MANAGE_FOLDERS, label: "Gérer les dossiers", category: "Documents" },

  { key: PERMISSIONS.KNOWLEDGE_READ, label: "Consulter la base de connaissances", category: "Base de connaissances" },
  { key: PERMISSIONS.KNOWLEDGE_CREATE, label: "Créer un article (et modifier ses propres articles)", category: "Base de connaissances" },
  { key: PERMISSIONS.KNOWLEDGE_UPDATE, label: "Modifier/publier les articles de tous les auteurs", category: "Base de connaissances" },
  { key: PERMISSIONS.KNOWLEDGE_MANAGE_CATEGORIES, label: "Gérer les catégories de la base de connaissances", category: "Base de connaissances" },

  { key: PERMISSIONS.LEAVE_CREATE, label: "Demander un congé", category: "Calendrier" },
  { key: PERMISSIONS.LEAVE_MANAGE, label: "Approuver/refuser les congés", category: "Calendrier" },
  { key: PERMISSIONS.EVENT_CREATE, label: "Créer un événement", category: "Calendrier" },

  { key: PERMISSIONS.OBJECTIVE_CREATE, label: "Créer un objectif", category: "Objectifs & KPI" },
  { key: PERMISSIONS.OBJECTIVE_READ, label: "Consulter les objectifs", category: "Objectifs & KPI" },
  { key: PERMISSIONS.OBJECTIVE_UPDATE, label: "Modifier un objectif / mettre à jour un indicateur", category: "Objectifs & KPI" },
  { key: PERMISSIONS.OBJECTIVE_DELETE, label: "Supprimer un objectif", category: "Objectifs & KPI" },

  { key: PERMISSIONS.WORKLOAD_READ, label: "Consulter la charge de l'équipe", category: "Charge de travail" },
  { key: PERMISSIONS.WORKLOAD_MANAGE, label: "Modifier la capacité des collaborateurs", category: "Charge de travail" },

  { key: PERMISSIONS.MESSAGE_CREATE, label: "Envoyer des messages", category: "Messagerie" },
  { key: PERMISSIONS.MESSAGE_READ, label: "Consulter la messagerie", category: "Messagerie" },

  { key: PERMISSIONS.AUTOMATION_MANAGE, label: "Créer et gérer les règles d'automatisation", category: "Automatisations" },
  { key: PERMISSIONS.AUTOMATION_READ, label: "Consulter les règles d'automatisation", category: "Automatisations" },

  { key: PERMISSIONS.DASHBOARD_READ, label: "Consulter les tableaux de bord", category: "Tableaux de bord" },

  { key: PERMISSIONS.REPORT_EXPORT, label: "Exporter des rapports (PDF/Excel/Word/présentation)", category: "Rapports" },

  { key: PERMISSIONS.SECURITY_AUDIT_READ, label: "Consulter le journal d'audit et l'état MFA", category: "Sécurité" },

  { key: PERMISSIONS.INTEGRATION_MANAGE, label: "Gérer les intégrations externes", category: "Intégrations" },

  { key: PERMISSIONS.DEPARTMENT_MANAGE, label: "Gérer un département", category: "Administration" },
  { key: PERMISSIONS.ADMINISTRATION_ACCESS, label: "Accéder à l'administration", category: "Administration" },
  { key: PERMISSIONS.ADMINISTRATION_USERS_MANAGE, label: "Gérer les utilisateurs", category: "Administration" },
  { key: PERMISSIONS.ADMINISTRATION_ROLES_MANAGE, label: "Gérer les rôles et permissions", category: "Administration" },

  { key: PERMISSIONS.GOVERNANCE_READ, label: "Consulter les instances de gouvernance (réunions, décisions)", category: "Gouvernance" },
  { key: PERMISSIONS.GOVERNANCE_MANAGE, label: "Créer et gérer les instances, réunions et décisions de gouvernance", category: "Gouvernance" },

  { key: PERMISSIONS.PROCESS_READ, label: "Consulter les processus et leurs exécutions", category: "Processus" },
  { key: PERMISSIONS.PROCESS_MANAGE, label: "Créer et gérer les processus, étapes et exécutions", category: "Processus" },

  { key: PERMISSIONS.RISK_READ, label: "Consulter le registre des risques organisationnel", category: "Risques" },
  { key: PERMISSIONS.RISK_MANAGE, label: "Créer et gérer les risques organisationnels", category: "Risques" },

  { key: PERMISSIONS.ENTITY_MANAGE, label: "Gérer les entités du groupe (sociétés, filiales, agences) et les jours fériés", category: "Multi-entités" },
  { key: PERMISSIONS.ENTITY_VIEW_ALL, label: "Voir toutes les entités du groupe, sans restriction de périmètre", category: "Multi-entités" },

  { key: PERMISSIONS.EXECUTIVE_VIEW, label: "Accéder au centre de commande exécutif (vue dirigeants)", category: "Centre de commande" },

  { key: PERMISSIONS.MARKETPLACE_MANAGE, label: "Gérer le catalogue d'applications (marketplace)", category: "Marketplace" },
  { key: PERMISSIONS.API_MANAGE, label: "Créer et révoquer des clés API", category: "API & intégrations" },

  { key: PERMISSIONS.SESSION_MANAGE, label: "Voir et révoquer les sessions actives des utilisateurs", category: "Sécurité" },
  { key: PERMISSIONS.DATA_BACKUP_MANAGE, label: "Exporter/importer une sauvegarde applicative", category: "Gestion des données" },
  { key: PERMISSIONS.TRASH_MANAGE, label: "Consulter et restaurer les éléments de la corbeille", category: "Gestion des données" },

  { key: PERMISSIONS.DECISION_MATRIX_MANAGE, label: "Créer et gérer des matrices de décision", category: "Décisions" },
  { key: PERMISSIONS.AI_GOVERNANCE_APPROVE, label: "Approuver ou rejeter les actions IA en attente de validation", category: "Gouvernance IA" },

  { key: PERMISSIONS.MEMORY_READ, label: "Consulter la mémoire organisationnelle (archives, décisions, retours d'expérience)", category: "Mémoire organisationnelle" },
  { key: PERMISSIONS.MEMORY_MANAGE, label: "Ajouter des entrées à la mémoire organisationnelle", category: "Mémoire organisationnelle" },

  { key: PERMISSIONS.SUCCESSION_READ, label: "Consulter les plans de succession et postes critiques", category: "Talent & Succession" },
  { key: PERMISSIONS.SUCCESSION_MANAGE, label: "Créer et gérer les plans de succession", category: "Talent & Succession" },

  { key: PERMISSIONS.PLATFORM_MANAGE, label: "Gérer le registre des organisations de la plateforme (multi-organisation)", category: "Plateforme" },
];

const ALL_PERMISSIONS = PERMISSION_CATALOG.map((p) => p.key);

/**
 * Matrice de permissions par défaut, utilisée par le seed pour peupler RolePermission.
 * Personnalisable ensuite depuis /administration/roles sans redéploiement.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionKey[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,

  DIRECTEUR_GENERAL: [
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_MANAGE,
    PERMISSIONS.PROGRAM_MANAGE,
    PERMISSIONS.PLAN_MANAGE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_VALIDATE,
    PERMISSIONS.PROJECT_EXPORT,
    PERMISSIONS.PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.SECTION_CREATE,
    PERMISSIONS.SECTION_UPDATE,
    PERMISSIONS.SECTION_DELETE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_VALIDATE,
    PERMISSIONS.ADMIN_REQUEST_VALIDATE,
    PERMISSIONS.EVALUATION_MANAGE,
    PERMISSIONS.COURRIER_MANAGE,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.TASK_EXPORT,
    PERMISSIONS.WORKFLOW_MANAGE,
    PERMISSIONS.MEETING_CREATE,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_UPDATE,
    PERMISSIONS.MEETING_MANAGE_PARTICIPANTS,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.DOCUMENT_MANAGE_FOLDERS,
    PERMISSIONS.KNOWLEDGE_MANAGE_CATEGORIES,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.ADMIN_REQUEST_CREATE,
    PERMISSIONS.ADMIN_REQUEST_READ,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.EVALUATION_READ,
    PERMISSIONS.COURRIER_READ,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.OBJECTIVE_CREATE,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.OBJECTIVE_UPDATE,
    PERMISSIONS.WORKLOAD_READ,
    PERMISSIONS.WORKLOAD_MANAGE,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.AUTOMATION_MANAGE,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.ADMINISTRATION_ACCESS,
    PERMISSIONS.SECURITY_AUDIT_READ,
    PERMISSIONS.INTEGRATION_MANAGE,
    PERMISSIONS.GOVERNANCE_MANAGE,
    PERMISSIONS.GOVERNANCE_READ,
    PERMISSIONS.PROCESS_MANAGE,
    PERMISSIONS.PROCESS_READ,
    PERMISSIONS.MEMORY_MANAGE,
    PERMISSIONS.MEMORY_READ,
    PERMISSIONS.SUCCESSION_MANAGE,
    PERMISSIONS.SUCCESSION_READ,
    PERMISSIONS.RISK_MANAGE,
    PERMISSIONS.RISK_READ,
    PERMISSIONS.ENTITY_MANAGE,
    PERMISSIONS.ENTITY_VIEW_ALL,
    PERMISSIONS.EXECUTIVE_VIEW,
    PERMISSIONS.MARKETPLACE_MANAGE,
    PERMISSIONS.API_MANAGE,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.SESSION_MANAGE,
    PERMISSIONS.DATA_BACKUP_MANAGE,
    PERMISSIONS.TRASH_MANAGE,
    PERMISSIONS.DECISION_MATRIX_MANAGE,
    PERMISSIONS.AI_GOVERNANCE_APPROVE,
  ],

  DIRECTEUR: [
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_MANAGE,
    PERMISSIONS.PROGRAM_MANAGE,
    PERMISSIONS.PLAN_MANAGE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_VALIDATE,
    PERMISSIONS.PROJECT_EXPORT,
    PERMISSIONS.PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.SECTION_CREATE,
    PERMISSIONS.SECTION_UPDATE,
    PERMISSIONS.SECTION_DELETE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_VALIDATE,
    PERMISSIONS.ADMIN_REQUEST_VALIDATE,
    PERMISSIONS.EVALUATION_MANAGE,
    PERMISSIONS.COURRIER_MANAGE,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.TASK_EXPORT,
    PERMISSIONS.MEETING_CREATE,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_UPDATE,
    PERMISSIONS.MEETING_MANAGE_PARTICIPANTS,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.DOCUMENT_MANAGE_FOLDERS,
    PERMISSIONS.KNOWLEDGE_MANAGE_CATEGORIES,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.ADMIN_REQUEST_CREATE,
    PERMISSIONS.ADMIN_REQUEST_READ,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.EVALUATION_READ,
    PERMISSIONS.COURRIER_READ,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.OBJECTIVE_CREATE,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.OBJECTIVE_UPDATE,
    PERMISSIONS.WORKLOAD_READ,
    PERMISSIONS.WORKLOAD_MANAGE,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.AUTOMATION_MANAGE,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.GOVERNANCE_MANAGE,
    PERMISSIONS.GOVERNANCE_READ,
    PERMISSIONS.PROCESS_MANAGE,
    PERMISSIONS.PROCESS_READ,
    PERMISSIONS.MEMORY_MANAGE,
    PERMISSIONS.MEMORY_READ,
    PERMISSIONS.SUCCESSION_MANAGE,
    PERMISSIONS.SUCCESSION_READ,
    PERMISSIONS.RISK_MANAGE,
    PERMISSIONS.RISK_READ,
  ],

  CHEF_DEPARTEMENT: [
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_MANAGE,
    PERMISSIONS.PROGRAM_MANAGE,
    PERMISSIONS.PLAN_MANAGE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_VALIDATE,
    PERMISSIONS.PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.SECTION_CREATE,
    PERMISSIONS.SECTION_UPDATE,
    PERMISSIONS.SECTION_DELETE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_VALIDATE,
    PERMISSIONS.ADMIN_REQUEST_VALIDATE,
    PERMISSIONS.EVALUATION_MANAGE,
    PERMISSIONS.COURRIER_MANAGE,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.MEETING_CREATE,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_UPDATE,
    PERMISSIONS.MEETING_MANAGE_PARTICIPANTS,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.DOCUMENT_MANAGE_FOLDERS,
    PERMISSIONS.KNOWLEDGE_MANAGE_CATEGORIES,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.ADMIN_REQUEST_CREATE,
    PERMISSIONS.ADMIN_REQUEST_READ,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.EVALUATION_READ,
    PERMISSIONS.COURRIER_READ,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.OBJECTIVE_CREATE,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.OBJECTIVE_UPDATE,
    PERMISSIONS.WORKLOAD_READ,
    PERMISSIONS.WORKLOAD_MANAGE,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.AUTOMATION_MANAGE,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.GOVERNANCE_READ,
    PERMISSIONS.PROCESS_MANAGE,
    PERMISSIONS.PROCESS_READ,
    PERMISSIONS.MEMORY_MANAGE,
    PERMISSIONS.MEMORY_READ,
    PERMISSIONS.SUCCESSION_MANAGE,
    PERMISSIONS.SUCCESSION_READ,
    PERMISSIONS.RISK_MANAGE,
    PERMISSIONS.RISK_READ,
  ],

  CHEF_PROJET: [
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_MANAGE,
    PERMISSIONS.PROGRAM_MANAGE,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_MANAGE_MEMBERS,
    PERMISSIONS.SECTION_CREATE,
    PERMISSIONS.SECTION_UPDATE,
    PERMISSIONS.SECTION_DELETE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_VALIDATE,
    PERMISSIONS.ADMIN_REQUEST_VALIDATE,
    PERMISSIONS.EVALUATION_MANAGE,
    PERMISSIONS.COURRIER_MANAGE,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.MEETING_CREATE,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_UPDATE,
    PERMISSIONS.MEETING_MANAGE_PARTICIPANTS,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.DOCUMENT_MANAGE_FOLDERS,
    PERMISSIONS.KNOWLEDGE_MANAGE_CATEGORIES,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.ADMIN_REQUEST_CREATE,
    PERMISSIONS.ADMIN_REQUEST_READ,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.EVALUATION_READ,
    PERMISSIONS.COURRIER_READ,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.OBJECTIVE_CREATE,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.OBJECTIVE_UPDATE,
    PERMISSIONS.WORKLOAD_READ,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.AUTOMATION_MANAGE,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.GOVERNANCE_READ,
    PERMISSIONS.PROCESS_MANAGE,
    PERMISSIONS.PROCESS_READ,
    PERMISSIONS.MEMORY_MANAGE,
    PERMISSIONS.MEMORY_READ,
    PERMISSIONS.RISK_MANAGE,
    PERMISSIONS.RISK_READ,
    PERMISSIONS.PROJECT_DELETE,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.TRASH_MANAGE,
    PERMISSIONS.DECISION_MATRIX_MANAGE,
  ],

  RESPONSABLE: [
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_MANAGE,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.SECTION_CREATE,
    PERMISSIONS.SECTION_UPDATE,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_VALIDATE,
    PERMISSIONS.ADMIN_REQUEST_VALIDATE,
    PERMISSIONS.EVALUATION_MANAGE,
    PERMISSIONS.COURRIER_MANAGE,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.MEETING_CREATE,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_UPDATE,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.ADMIN_REQUEST_CREATE,
    PERMISSIONS.ADMIN_REQUEST_READ,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.EVALUATION_READ,
    PERMISSIONS.COURRIER_READ,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.OBJECTIVE_CREATE,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.OBJECTIVE_UPDATE,
    PERMISSIONS.WORKLOAD_READ,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.PROCESS_READ,
    PERMISSIONS.MEMORY_READ,
    PERMISSIONS.SUCCESSION_READ,
    PERMISSIONS.RISK_READ,
  ],

  MANAGER: [
    PERMISSIONS.CRM_READ,
    PERMISSIONS.CRM_MANAGE,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.MEETING_CREATE,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.MEETING_UPDATE,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_UPDATE,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.ADMIN_REQUEST_CREATE,
    PERMISSIONS.ADMIN_REQUEST_READ,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.EVALUATION_READ,
    PERMISSIONS.COURRIER_READ,
    PERMISSIONS.LEAVE_MANAGE,
    PERMISSIONS.EVENT_CREATE,
    PERMISSIONS.OBJECTIVE_CREATE,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.OBJECTIVE_UPDATE,
    PERMISSIONS.WORKLOAD_READ,
    PERMISSIONS.WORKLOAD_MANAGE,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.PROCESS_READ,
    PERMISSIONS.MEMORY_READ,
    PERMISSIONS.SUCCESSION_READ,
    PERMISSIONS.RISK_READ,
  ],

  COLLABORATEUR: [
    PERMISSIONS.CRM_READ,
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.DOCUMENT_CREATE,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.KNOWLEDGE_CREATE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.ADMIN_REQUEST_CREATE,
    PERMISSIONS.ADMIN_REQUEST_READ,
    PERMISSIONS.PLAN_READ,
    PERMISSIONS.EVALUATION_READ,
    PERMISSIONS.COURRIER_READ,
    PERMISSIONS.OBJECTIVE_CREATE,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.OBJECTIVE_UPDATE,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
  ],

  CONSULTANT_EXTERNE: [
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
  ],

  PRESTATAIRE: [
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_COMMENT,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
  ],

  INVITE: [
    PERMISSIONS.PROGRAM_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.MEETING_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.OBJECTIVE_READ,
    PERMISSIONS.MESSAGE_CREATE,
    PERMISSIONS.MESSAGE_READ,
  ],
};

export function hasPermission(
  permissions: string[] | undefined,
  key: PermissionKey
): boolean {
  return !!permissions?.includes(key);
}

export function requirePermission(
  permissions: string[] | undefined,
  key: PermissionKey
): void {
  if (!hasPermission(permissions, key)) {
    throw new Error(`Permission refusée: ${key}`);
  }
}

// hasScopedPermission/requireScopedPermission (portée département/projet,
// cahier des charges §19) vivent dans src/lib/permissions-scoped.ts — elles
// touchent prisma, contrairement au reste de ce fichier qui doit rester
// importable sans risque depuis un composant client (nav-config.ts etc.).
