// Tables couvertes par le retrofit multi-tenant (organizationId +
// platformOrganizationId + RLS, Phase 1 — 17 lots, cloturee le 2026-08-20).
// Source unique partagee entre scripts/setup-local-rls-test-role.ts et
// scripts/setup-production-tenant-role.ts pour eviter toute divergence.
// Etendre cette liste ne suffit pas a "couvrir" un nouveau modele : il faut
// d'abord la migration organizationId + RLS (voir prisma/schema.prisma et
// le commentaire sur PlatformOrganization) puis relancer les deux scripts
// setup-*-tenant-role pour que le role scope y ait acces.
export const COVERED_TABLES = [
  "User",
  "Department",
  "Team",
  "Project",
  "Task",
  "ProjectSection",
  "Document",
  "Meeting",
  "DocumentFolder",
  "Whiteboard",
  "ProjectMember",
  "ProjectRisk",
  "ProjectMilestone",
  "ProjectDeliverable",
  "ProjectResource",
  "SectionComment",
  "TaskAssignee",
  "ChecklistItem",
  "TaskComment",
  "TaskDependency",
  "DocumentAccess",
  "DocumentVersion",
  "MeetingParticipant",
  "MeetingDecision",
  "MeetingExternalParticipant",
  "Competence",
  "UserCompetence",
  "KnowledgeCategory",
  "KnowledgeArticle",
  "Leave",
  "Event",
  "Objective",
  "Indicator",
  "Evaluation",
  "EvaluationCritere",
  "Conversation",
  "ConversationParticipant",
  "Message",
  "Reaction",
  "Notification",
  "CrmOrganization",
  "CrmContact",
  "PortalAccount",
  "PortalInviteToken",
  "CrmOpportunity",
  "CrmInteraction",
  "Contract",
  "PortalMessage",
  "DecisionOutcome",
  "Poste",
  "PosteResponsabilite",
  "SuccessionPlan",
  "SuccessionCandidate",
  "Site",
  "Delegation",
  "StrategicAxis",
  "SwotItem",
  "Plan",
  "Programme",
  "ProgrammeRisk",
  "GovernanceInstance",
  "GovernanceInstanceMember",
  "GovernanceMeeting",
  "GovernanceMeetingParticipant",
  "GovernanceMeetingDocument",
  "GovernanceDecision",
  "Processus",
  "ProcessusEtape",
  "ProcessusVersion",
  "ProcessusExecution",
  "ProcessusExecutionEtape",
  "ProcessusDocument",
  "OrganizationalRisk",
  "ComplianceObligation",
  "ComplianceControl",
  "ComplianceObligationDocument",
  "NonConformite",
  "NonConformiteAction",
  "QualityDocument",
  "QualityControl",
  "QualityChecklistItem",
  "QualityClaim",
  "AuditPlan",
  "AuditPlanMember",
  "AuditPlanDocument",
  "AuditMission",
  "AuditFinding",
  "Incident",
  "ChangeRequest",
  "ValidationWorkflow",
  "ValidationWorkflowStep",
  "TaskValidationRun",
  "TaskApproval",
  "AdminRequest",
  "AdminRequestValidationRun",
  "AdminRequestApproval",
  "Courrier",
  "AutomationCondition",
  "OrchestrationPlaybook",
  "AutomationRule",
  "AutomationExecution",
  "PendingAiAction",
  "OrgDesignDraft",
  "DataClassification",
  "Transformation",
  "OrganizationalMemoryEntry",
  "DecisionMatrix",
  "DecisionOption",
  "AuditLog",
  "Integration",
  "IntegrationEvent",
  "DashboardWidgetPreference",
  "AiAgentInsight",
  "MetricSnapshot",
  "Dependency",
  "Scenario",
  "Beneficiaire",
  "Entity",
  "Holiday",
  "Tag",
  "EntityTag",
  "ApiKey",
  "PasswordResetToken",
  "PermissionOverride",
  "TeamMember",
  "Stakeholder",
  "StakeholderProject",
  "StakeholderCommunication",
  "UserSession",
  // Project Studio (2026-08-25) — pas de migration organizationId/RLS
  // dediee (retrofit multi-tenant en pause), mais ces tables ont deja la
  // colonne organizationId et passent par withTenantScopedSession comme le
  // reste des actions projet : sans l'octroi ci-dessous, le role scope
  // (proprietaire zero) n'a aucun droit dessus et toute ecriture echoue des
  // qu'un organizationId est renseigne.
  "ProjectIdea",
  "ProjectConceptNote",
  "Financement",
  "ProjectDiagnostic",
  "ProblemTreeNode",
  "SolutionTreeNode",
  "TheoryOfChangeNode",
  "LogframeRow",
  "RaciAssignment",
  "BudgetLine",
  "FundingOpportunity",
  "ProjectAssumption",
  "ProjectChangeRequest",
  "ProcurementItem",
  "ProjectContract",
  "ProjectContractPayment",
  "CommunicationPlanEntry",
  // Demande de report de date sur une tache (2026-09-04) — meme raison que
  // Project Studio ci-dessus : passe par withTenantScopedSession, donc sans
  // l'octroi le role scope n'a aucun droit dessus.
  "TaskDateChangeRequest",
];
